services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_CLIENT=pg
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=measure
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=measure
      - GEMINI_API_KEY=
    command: ./run-migrations.sh
    expose:
      - "3000"
    ports:
      - "3000:3000"

  db:
    image: postgres:alpine
    container_name: measure_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=measure
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=measure
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: